### ISSUE TITLE
Device & Session QR Codes cant be created when impersonating a User 

### ISSUE THREAD

**Issue by Rick26L** [nextcloud/impersonate#132] opened 2021-03-03 09:39 UTC
After Migration to Nextcloud 20 is it not possible to create new App password while impersonate a other user. 

Screenshot when direct logged in with a user account: 
![image](https://user-images.githubusercontent.com/36233183/109785974-f8c45400-7c0c-11eb-92d8-f3d07840118b.png)

Screenshot when trying to create a app token while impersonating a user: 
![image](https://user-images.githubusercontent.com/36233183/109786001-0083f880-7c0d-11eb-98c8-79f8afc25cc5.png)

**Comment by blizzz** [comment] 2021-03-03 10:11
duplicate of https://github.com/nextcloud/impersonate/issues/34

**Closed by blizzz** 2021-03-03 10:11 UTC
