### ISSUE TITLE
Generating App-Pins does not work

### ISSUE THREAD

**Issue by ManOki** [nextcloud/impersonate#10] opened 2017-07-14 15:10 UTC
Hi,

when i generate an app pin while logged in by impersonating, the generated app pin result shows the name of the admin user and the generated app pin is not valid (either user nor admin).

Greets, ManOki

**Comment by schnappijedi** [comment] 2017-07-27 23:01
Same issue. Confirmed.

**Comment by lorenz** [comment] 2017-08-14 04:22
I investigated this, basically boils down to two issues:

1. `$loginName` is being set to the loginName of the currently logged in session (admin user). This can be trivially fixed:
```diff
--- a/settings/Controller/AuthSettingsController.php
+++ b/settings/Controller/AuthSettingsController.php
@@ -136,7 +136,7 @@ class AuthSettingsController extends Controller {
                }
 
                $token = $this->generateRandomDeviceToken();
-               $deviceToken = $this->tokenProvider->generateToken($token, $this->uid, $loginName, $password, $name, IToken::PERMANENT_TOKEN);
+               $deviceToken = $this->tokenProvider->generateToken($token, $this->uid, $this->uid, $password, $name, IToken::PERMANENT_TOKEN);
                $tokenData = $deviceToken->jsonSerialize();
                $tokenData['canDelete'] = true;
 ```

2. The auth tokens carry the original password that was used to create them and will be invalidated as soon as that happens. Since the password is taken from the admin user, the resulting tokens are never actually valid. This is much harder to fix since we don't actually know the users current password. I don't think this can be done without lots of changes to login rollover (password changes, revokes, ...).

**Comment by ManOki** [comment] 2017-08-14 13:17
I don't get the 2. point: Does that mean, if i change my normal password, all App-Pins are invalidated as well? Is this documented somewhere? By now, i thought, those pins are randomly generated "2nd class passwords".

**Comment by lorenz** [comment] 2017-08-14 18:44
Yes, as far as I can tell from the code, that is the case (don't quote me on that, I'm not a NextCloud developer).

**Comment by ManOki** [comment] 2017-08-15 08:48
Seems there is already an issue for that: nextcloud/server#2581

**Comment by blizzz** [comment] 2021-01-13 21:31
App tokens can only be generated by the user themselves, because it encrypts the password. When a user changes their password, the app tokens are updated. By design it is not possible for an impersonator to create an app token.

**Closed by blizzz** 2021-01-13 21:31 UTC
