### ISSUE TITLE
As of Nextcloud 18, impersonate no longer works?

### ISSUE THREAD

**Issue by Aesculapius** [nextcloud/impersonate#89] opened 2020-01-28 10:37 UTC
Running impersonate 1.5, Nextcloud 18, I no longer see the option in the three-bullet list next to a user account...

![image](https://user-images.githubusercontent.com/617061/73256663-a0798200-41c2-11ea-876c-234c9df4409f.png)

**Comment by blizzz** [comment] 2020-01-28 13:42
WFM :tm: 

- are you in a group whitelisted to use impersonate?
- is it really enabled :)
- are there any errors on the browser log?

**Comment by dea-75** [comment] 2020-03-24 20:28
On Nextcloud 18.0.3 I've random problem.
Randomly I can use "impersonate", randomly I can't see the "impersonate" choise in the menù.
I've tried on Firefox & Chrome

**Comment by blizzz** [comment] 2020-04-22 11:23
For now, increase the delay to, say, 5000, there will be more attempts. Maybe that helps.

Long term… @skjnldsv what can we do about this to have this reliable and in a more sane manner?

**Comment by jpubb** [comment] 2020-09-25 20:18
Version 18.04 here.  Impersonate works fine for me.

**Comment by skjnldsv** [comment] 2020-09-30 08:25
Works here too :)

**Comment by skjnldsv** [comment] 2020-09-30 08:33
As I cannot reproduce the original issue anymore, I will close this ticket. If this is still happening please make sure to **upgrade** to the **latest** version. After that, feel free to reopen.

**Closed by skjnldsv** 2020-09-30 08:33 UTC
Labels: 0. Needs triage, bug
